### ISSUE TITLE
Rust Rewrite

### ISSUE THREAD

**Issue by sa6ta6ni6c** [Tenclea/YANG#146]
Hello!

I appreciate your work with this tool. What’s the license status? I want to make a full rewrite of it in Rust, for learning and to possibly speed up the code generation and checking.

Regards,
Dan

**Comment by Tenclea** [comment]
Oh nice! That's actually an idea I got as well since I really need to get into rust.. I'll check your code out once you've published it, it will be a great example, I'm sure :)
As for the licence, I guess as long as you do not copy-paste my code, you're free to do anything you want.

...feel free to credit me though ;p
