### ISSUE TITLE
Proxys

### ISSUE THREAD

**Issue by Yunikee** [Tenclea/YANG#2]
The code seems to be fine, but its checking like 3 codes in 5 seconds or less, because of the proxies. I put 10k of HTTP proxies and in the final i only get arround 12 working proxies, maybe its because of the number you put on app.js i dont know, check it if you can

**Comment by Tenclea** [comment]
The program keeps track of every working proxy, and if you enabled it in the config file, once you run out of proxies, it will restart itself with the working proxies list. I don't think speed is the problem here, you should try to add more recent proxies maybe.
With an updated list of fresh proxies I manage to get about a hundred  working threads at the same time.
Check your proxies, proxies provider and also that Discord didn't block them.

I could code a proxy check if you want

**Comment by Yunikee** [comment]
Uhmm, thanks. Oh, it will be very kind, yes please

**Comment by Yunikee** [comment]
By the way, do you have discord? Maybe we can talk there

**Comment by Yunikee** [comment]
Oh, i put a 10k proxies and it says "loaded 3045" there is a limit of proxies?

**Comment by Tenclea** [comment]
> By the way, do you have discord? Maybe we can talk there
Sure, it's Tenclea#1337

**Comment by Tenclea** [comment]
> Oh, i put a 10k proxies and it says "loaded 3045" there is a limit of proxies?

The bot automatically removes duplicates, so you might want to check your list on a website like [this one](https://onlinetexttools.com/remove-duplicate-text-lines).
